# permissions for end users to edit hostedzones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hostedzone-editor-role
rules:
- apiGroups:
  - route53.aws.czan.io
  resources:
  - hostedzones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - route53.aws.czan.io
  resources:
  - hostedzones/status
  verbs:
  - get
