# permissions for end users to view hostedzones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hostedzone-viewer-role
rules:
- apiGroups:
  - route53.aws.czan.io
  resources:
  - hostedzones
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - route53.aws.czan.io
  resources:
  - hostedzones/status
  verbs:
  - get
