# permissions for end users to edit resourcerecords.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resourcerecord-editor-role
rules:
- apiGroups:
  - route53.aws.czan.io
  resources:
  - resourcerecords
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - route53.aws.czan.io
  resources:
  - resourcerecords/status
  verbs:
  - get
