# permissions for end users to view resourcerecords.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resourcerecord-viewer-role
rules:
- apiGroups:
  - route53.aws.czan.io
  resources:
  - resourcerecords
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - route53.aws.czan.io
  resources:
  - resourcerecords/status
  verbs:
  - get
