---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - route53.aws.czan.io
  resources:
  - hostedzones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - route53.aws.czan.io
  resources:
  - hostedzones/finalizers
  verbs:
  - update
- apiGroups:
  - route53.aws.czan.io
  resources:
  - hostedzones/status
  verbs:
  - get
  - patch
  - update
