apiVersion: route53.aws.czan.io/v1
kind: HostedZone
metadata:
  name: hostedzone.myexample.com
spec:

---

apiVersion: route53.aws.czan.io/v1
kind: HostedZone
metadata:
  name: my.hostedzone.myexample.com
spec:
  delegateOf:
    hostedZoneRef:
      name: hostedzone.myexample.com
    roleARN: arn:aws:iam::696758779764:role/route53admin

---

apiVersion: route53.aws.czan.io/v1
kind: ResourceRecord
metadata:
  name: resourcerecord-sample
spec:
  hostedZoneRef:
    name: my.hostedzone.myexample.com
  recordSet:
    name: my.hostedzone.myexample.com
    type: "A"
    ttl: 300
    resourceRecords:
    - value: 10.1.2.3
