apiVersion: route53.aws.czan.io/v1
kind: HostedZone
metadata:
  name: hostedzone.myexample.com
spec:

---

apiVersion: route53.aws.czan.io/v1
kind: HostedZone
metadata:
  name: my.hostedzone.myexample.com
spec:
  delegateOf:
    hostedZoneRef:
      name: hostedzone.myexample.com
    roleARN: arn:aws:iam::696758779764:role/route53admin

