apiVersion: route53.aws.czan.io/v1
kind: ResourceRecord
metadata:
  name: resourcerecord-sample
spec:
  hostedZone:
    name: my.hostedzone.myexample.com
  recordSet:
    name: my.hostedzone.myexample.com
    type: "A"
    ttl: 300
    resourceRecords:
    - value: 10.1.2.3
